import type { NextPage } from 'next'
import Head from 'next/head'

import { Navbar, Welcome, Footer, Services, Transactions } from '../components';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Crypto Web3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='min-h-screen'>
        <div className='gradient-bg-welcome'>
          <Navbar />
          <Welcome />
        </div>
        <Services />
        <Transactions />
        <Footer />
      </div>
    </>
  )
}

export default Home
